version: '3.9'

services:
  master:
    container_name: locust-master
    build:
      context: ./
    ports:
     - 8089:8089
    volumes:
      - ./:/code/
    command: -f /code/locustfiles/locustfile.py --master
    env_file:
      - .env

  worker:
    volumes:
      - ./:/code/
    build:
      context: ./
    command: -f /code/locustfiles/locustfile.py --worker --master-host master
    env_file:
      - .env
    depends_on:
      - master
