version: "3.9"

services:
  main:
    container_name: locust-main
    build:
      context: ./
      dockerfile: ./dockerfiles/python311/Dockerfile
    ports:
      - 8089:8089
    volumes:
      - ./:/code/
    command: |
      bash -c 'locust -f /code/src/locustfile.py --master \
      --config /code/src/locust.conf'
    env_file:
      - .env

  worker:
    volumes:
      - ./:/code/
    build:
      context: ./
      dockerfile: ./dockerfiles/python311/Dockerfile
    command: |
      bash -c 'locust -f /code/src/locustfile.py --worker \
      --master-host main --config /code/src/locust.conf'
    env_file:
      - .env
    depends_on:
      - main
