name: Check Locust Stress Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the Dependencies
        run: |
          echo "Upgrading pip ...."
          python -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt && pip install -r requirements-dev.txt

      - name: Check Linter
        run: |
          echo "Checking black formatting..."
          python3 -m black --check .

          echo "Checking isort formatting..."
          python3 -m isort --check .

          echo "Checking flake8 formatting..."
          python3 -m flake8 .


      - name: Run the tests & Generate coverage report
        run: |
          pytest -k 'not integration'
          python3 -m locust -f src/locustfile.py \
          --headless -u 1 -r 5 --run-time=5 --exit-code-on-error 1
